version: '3.6'

services:
  mod-ui:
    container_name: mod-ui
    image: guysoft/mod-ui
    restart: always
    volumes:
      - /dev/snd:/dev/snd:rw
      - /dev/shm:/dev/shm:rw
    tty: true
    user: "1000"
    ports:
      - "8888:8888"
volumes:
  mod-ui-data:
    driver: local
    external:
      name: mod-ui-data
