version: '3.6'

services:
  mod-ui:
    container_name: mod-ui
    build:
      context: .
    restart: always
    volumes:
      - /dev/snd:/dev/snd:rw
      - /dev/shm:/dev/shm:rw
      - type: volume
        source: mod-ui-data
        target: /home/moduser/mod-ui/data
    tty: true
    user: "1000"
    ports:
      - "8888:8888"

volumes:
  mod-ui-data:
    driver: local
    external:
      name: mod-ui-data

